/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import util.Util;

/**
 *
 * @author Moonie
 */
public class JDlgClientes extends javax.swing.JDialog {

    /**
     * Creates new form JDlgClientes
     */
    public JDlgClientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Usuários");
        setLocationRelativeTo(null);
        Util.habilitar(false, mb_jTxtNome, mb_jTxtCodigo, mb_jTxtApelido,mb_jFmtCpf, mb_jCboNivel,
                        mb_jFmtDataNasc, mb_jPsdSenha, mb_jCboNivel, mb_jChbAtivo,
                        mb_jBtnConfirmar, mb_jBtnCancelar, mb_jCboEstado, mb_jCboGenero, mb_jFmtCep, mb_jFmtEmail,
                        mb_jFmtRg, mb_jFmtTelefone, mb_jTxtBairro, mb_jTxtEndereco
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        mb_jBtnIncluir = new javax.swing.JButton();
        mb_jBtnExcluir = new javax.swing.JButton();
        mb_jBtnAlterar = new javax.swing.JButton();
        mb_jBtnPesquisar = new javax.swing.JButton();
        mb_jBtnConfirmar = new javax.swing.JButton();
        mb_jBtnCancelar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        mb_jFmtCpf = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        mb_jFmtDataNasc = new javax.swing.JFormattedTextField();
        mb_jTxtCodigo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        mb_jCboNivel = new javax.swing.JComboBox<>();
        mb_jTxtNome = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        mb_jTxtApelido = new javax.swing.JTextField();
        mb_jPsdSenha = new javax.swing.JPasswordField();
        mb_jChbAtivo = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        mb_jFmtEmail = new javax.swing.JFormattedTextField();
        mb_jFmtTelefone = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        mb_jCboGenero = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        mb_jFmtCep = new javax.swing.JFormattedTextField();
        jLabel19 = new javax.swing.JLabel();
        mb_jTxtEndereco = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        mb_jTxtBairro = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        mb_jFmtRg = new javax.swing.JFormattedTextField();
        jLabel22 = new javax.swing.JLabel();
        mb_jCboEstado = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));

        mb_jBtnIncluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mb_jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/adicionar-usuario.png"))); // NOI18N
        mb_jBtnIncluir.setText("Incluir");
        mb_jBtnIncluir.setIconTextGap(15);
        mb_jBtnIncluir.setMaximumSize(new java.awt.Dimension(133, 33));
        mb_jBtnIncluir.setMinimumSize(new java.awt.Dimension(133, 33));
        mb_jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mb_jBtnIncluirActionPerformed(evt);
            }
        });

        mb_jBtnExcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mb_jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cruz.png"))); // NOI18N
        mb_jBtnExcluir.setText("Excluir");
        mb_jBtnExcluir.setIconTextGap(15);
        mb_jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mb_jBtnExcluirActionPerformed(evt);
            }
        });

        mb_jBtnAlterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mb_jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        mb_jBtnAlterar.setText("Alterar");
        mb_jBtnAlterar.setIconTextGap(16);
        mb_jBtnAlterar.setMaximumSize(new java.awt.Dimension(133, 33));
        mb_jBtnAlterar.setMinimumSize(new java.awt.Dimension(133, 33));
        mb_jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mb_jBtnAlterarActionPerformed(evt);
            }
        });

        mb_jBtnPesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mb_jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar-alt.png"))); // NOI18N
        mb_jBtnPesquisar.setText("Pesquisar");
        mb_jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mb_jBtnPesquisarActionPerformed(evt);
            }
        });

        mb_jBtnConfirmar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mb_jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/afirmativo.png"))); // NOI18N
        mb_jBtnConfirmar.setText("Confirmar");
        mb_jBtnConfirmar.setIconTextGap(15);

        mb_jBtnCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mb_jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/polegares-para-baixo.png"))); // NOI18N
        mb_jBtnCancelar.setText("Cancelar");
        mb_jBtnCancelar.setIconTextGap(15);
        mb_jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mb_jBtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mb_jBtnIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mb_jBtnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mb_jBtnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mb_jBtnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mb_jBtnConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mb_jBtnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mb_jBtnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mb_jBtnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mb_jBtnConfirmar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mb_jBtnExcluir)
                    .addComponent(mb_jBtnPesquisar)
                    .addComponent(mb_jBtnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setText("Cpf");

        mb_jFmtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mb_jFmtCpfActionPerformed(evt);
            }
        });

        jLabel9.setText("Data de Nascimento");

        jLabel10.setText("Código");

        mb_jFmtDataNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mb_jFmtDataNascActionPerformed(evt);
            }
        });

        jLabel11.setText("Nível");

        jLabel12.setText("Nome");

        mb_jCboNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Usuario", "Cliente", " " }));
        mb_jCboNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mb_jCboNivelActionPerformed(evt);
            }
        });

        jLabel13.setText("Senha");

        jLabel14.setText("Apelido");

        mb_jPsdSenha.setText("123456");
        mb_jPsdSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mb_jPsdSenhaActionPerformed(evt);
            }
        });

        mb_jChbAtivo.setText("Ativo");

        jLabel15.setText("Email");

        jLabel16.setText("Telefone");

        mb_jFmtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mb_jFmtEmailActionPerformed(evt);
            }
        });

        jLabel17.setText("Gênero");

        mb_jCboGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Homem", "Mulher", "Não Binário", " " }));
        mb_jCboGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mb_jCboGeneroActionPerformed(evt);
            }
        });

        jLabel18.setText("Cep");

        jLabel19.setText("Endereço");

        jLabel20.setText("Bairro");

        jLabel21.setText("Rg");

        mb_jFmtRg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mb_jFmtRgActionPerformed(evt);
            }
        });

        jLabel22.setText("Estado");

        mb_jCboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        mb_jCboEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mb_jCboEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel22)
                            .addComponent(mb_jCboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mb_jChbAtivo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel11)
                                            .addGap(165, 165, 165))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(mb_jTxtApelido, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(mb_jTxtNome, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(mb_jTxtCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                                                .addComponent(jLabel12))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(18, 18, 18)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(mb_jCboNivel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jLabel15)
                                                            .addGap(0, 0, Short.MAX_VALUE))
                                                        .addComponent(mb_jFmtEmail)))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(17, 17, 17)
                                                    .addComponent(mb_jFmtTelefone))))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel8)
                                                .addComponent(mb_jFmtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel14))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel16)
                                                .addComponent(jLabel9)
                                                .addComponent(mb_jFmtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel21)
                                                .addComponent(mb_jFmtRg, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(mb_jPsdSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel20)
                                        .addComponent(jLabel17)
                                        .addComponent(mb_jCboGenero, 0, 190, Short.MAX_VALUE)
                                        .addComponent(jLabel18)
                                        .addComponent(mb_jFmtCep)
                                        .addComponent(mb_jTxtEndereco)
                                        .addComponent(jLabel19))
                                    .addComponent(mb_jTxtBairro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(mb_jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mb_jCboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mb_jCboGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mb_jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mb_jFmtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mb_jFmtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(26, 26, 26)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mb_jFmtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mb_jTxtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mb_jTxtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(mb_jTxtApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mb_jFmtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mb_jFmtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mb_jPsdSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel22)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(mb_jCboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel21)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(mb_jFmtRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23)
                .addComponent(mb_jChbAtivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mb_jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mb_jBtnIncluirActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, mb_jTxtNome, mb_jTxtCodigo, mb_jTxtApelido,mb_jFmtCpf, mb_jCboNivel,
                        mb_jFmtDataNasc, mb_jPsdSenha, mb_jCboNivel, mb_jChbAtivo,
                        mb_jBtnConfirmar, mb_jBtnCancelar, mb_jCboEstado, mb_jCboGenero, mb_jFmtCep, mb_jFmtEmail,
                        mb_jFmtRg, mb_jFmtTelefone, mb_jTxtBairro, mb_jTxtEndereco   );
        Util.habilitar(false, mb_jBtnIncluir, mb_jBtnAlterar, mb_jBtnExcluir, mb_jBtnPesquisar);
    }//GEN-LAST:event_mb_jBtnIncluirActionPerformed

    private void mb_jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mb_jBtnExcluirActionPerformed
        // TODO add your handling code here:
        Util.limpar( mb_jTxtNome, mb_jTxtCodigo, mb_jTxtApelido,mb_jFmtCpf, mb_jCboNivel,
                        mb_jFmtDataNasc, mb_jPsdSenha, mb_jCboNivel, mb_jChbAtivo,
                        mb_jBtnConfirmar, mb_jBtnCancelar, mb_jCboEstado, mb_jCboGenero, mb_jFmtCep, mb_jFmtEmail,
                        mb_jFmtRg, mb_jFmtTelefone, mb_jTxtBairro, mb_jTxtEndereco   );
        //Util.habilitar(false, mb_jBtnIncluir, mb_jBtnAlterar, mb_jBtnExcluir, mb_jBtnPesquisar);
    }//GEN-LAST:event_mb_jBtnExcluirActionPerformed

    private void mb_jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mb_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false, mb_jTxtNome, mb_jTxtCodigo, mb_jTxtApelido,mb_jFmtCpf, mb_jCboNivel,
                        mb_jFmtDataNasc, mb_jPsdSenha, mb_jCboNivel, mb_jChbAtivo,
                        mb_jBtnConfirmar, mb_jBtnCancelar, mb_jCboEstado, mb_jCboGenero, mb_jFmtCep, mb_jFmtEmail,
                        mb_jFmtRg, mb_jFmtTelefone, mb_jTxtBairro, mb_jTxtEndereco   );
        Util.habilitar(true, mb_jBtnIncluir, mb_jBtnAlterar, mb_jBtnExcluir, mb_jBtnPesquisar);
    }//GEN-LAST:event_mb_jBtnCancelarActionPerformed

    private void mb_jFmtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mb_jFmtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mb_jFmtCpfActionPerformed

    private void mb_jFmtDataNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mb_jFmtDataNascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mb_jFmtDataNascActionPerformed

    private void mb_jCboNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mb_jCboNivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mb_jCboNivelActionPerformed

    private void mb_jPsdSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mb_jPsdSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mb_jPsdSenhaActionPerformed

    private void mb_jCboGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mb_jCboGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mb_jCboGeneroActionPerformed

    private void mb_jFmtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mb_jFmtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mb_jFmtEmailActionPerformed

    private void mb_jFmtRgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mb_jFmtRgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mb_jFmtRgActionPerformed

    private void mb_jCboEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mb_jCboEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mb_jCboEstadoActionPerformed

    private void mb_jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mb_jBtnAlterarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, mb_jTxtNome, mb_jTxtCodigo, mb_jTxtApelido,mb_jFmtCpf, mb_jCboNivel,
                        mb_jFmtDataNasc, mb_jPsdSenha, mb_jCboNivel, mb_jChbAtivo,
                        mb_jBtnConfirmar, mb_jBtnCancelar, mb_jCboEstado, mb_jCboGenero, mb_jFmtCep, mb_jFmtEmail,
                        mb_jFmtRg, mb_jFmtTelefone, mb_jTxtBairro, mb_jTxtEndereco   );
        Util.habilitar(false, mb_jBtnIncluir, mb_jBtnAlterar, mb_jBtnExcluir, mb_jBtnPesquisar);
    }//GEN-LAST:event_mb_jBtnAlterarActionPerformed

    private void mb_jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mb_jBtnPesquisarActionPerformed
        // TODO add your handling code here:
        JDlgClientesPesquisar jDlgClientesPesquisar = new JDlgClientesPesquisar(null, true);
        jDlgClientesPesquisar.setTelaPai(this);
        jDlgClientesPesquisar.setVisible(true);
    }//GEN-LAST:event_mb_jBtnPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgClientes dialog = new JDlgClientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton mb_jBtnAlterar;
    private javax.swing.JButton mb_jBtnCancelar;
    private javax.swing.JButton mb_jBtnConfirmar;
    private javax.swing.JButton mb_jBtnExcluir;
    private javax.swing.JButton mb_jBtnIncluir;
    private javax.swing.JButton mb_jBtnPesquisar;
    private javax.swing.JComboBox<String> mb_jCboEstado;
    private javax.swing.JComboBox<String> mb_jCboGenero;
    private javax.swing.JComboBox<String> mb_jCboNivel;
    private javax.swing.JCheckBox mb_jChbAtivo;
    private javax.swing.JFormattedTextField mb_jFmtCep;
    private javax.swing.JFormattedTextField mb_jFmtCpf;
    private javax.swing.JFormattedTextField mb_jFmtDataNasc;
    private javax.swing.JFormattedTextField mb_jFmtEmail;
    private javax.swing.JFormattedTextField mb_jFmtRg;
    private javax.swing.JFormattedTextField mb_jFmtTelefone;
    private javax.swing.JPasswordField mb_jPsdSenha;
    private javax.swing.JTextField mb_jTxtApelido;
    private javax.swing.JTextField mb_jTxtBairro;
    private javax.swing.JTextField mb_jTxtCodigo;
    private javax.swing.JTextField mb_jTxtEndereco;
    private javax.swing.JTextField mb_jTxtNome;
    // End of variables declaration//GEN-END:variables
}
